Update forward.yml

diff --git a/.github/workflows/forward.yml b/.github/workflows/forward.yml
--- a/.github/workflows/forward.yml
+++ b/.github/workflows/forward.yml
@@ -10,29 +10,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+      - uses: actions/checkout@v4
 
-      - name: Setup Python
-        uses: actions/setup-python@v5
+      - uses: actions/setup-python@v5
         with:
           python-version: "3.10"
 
-      - name: Install Requests
-        run: pip install requests
+      - run: pip install requests
 
-      - name: Debug Secrets
+      - name: Check Secrets
         env:
           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
           CHANNEL_IDS: ${{ secrets.CHANNEL_IDS }}
         run: |
-          echo "BOT_TOKEN Exists:"
-          [ -n "$BOT_TOKEN" ] && echo "YES" || echo "NO"
+          echo "BOT_TOKEN:"
+          [ -n "$BOT_TOKEN" ] && echo "FOUND" || echo "MISSING"
 
-          echo "CHANNEL_IDS Exists:"
-          [ -n "$CHANNEL_IDS" ] && echo "YES" || echo "NO"
+          echo "CHANNEL_IDS:"
+          [ -n "$CHANNEL_IDS" ] && echo "FOUND" || echo "MISSING"
 
       - name: Run Forwarder
         env:
